// Generated by https://quicktype.io

export interface ProxyUser {
    _id: number;
    id: number;
    proxy_nick: string;
    proxy_pid: number;
    proxy_lv: number;
    balance: number;
    lock_balance: number;
    change_time: number;
    login_time: number;
    login_ip: string;
    regin_time: number;
    regin_ip: string;
    proxy_number: number;
    user_number: number;
    status: number;
    proxy_user_type: number;
    package_id: number;
    game_img: string;
    proxy_img: string;
    income: number;
}
